config/routes.rb
Crm::Application.routes.draw do
  devise_for :members

  resources :lead5s

  resources :lead4s

  resources :lead3s

  resources :lead2s

  resources :lead1s
  root :to =>'home#index'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index

 end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <style>
    body{
        padding-top: 0px;
        background-image: url('/assets/home_p1.jpg');
        background-repeat: no-repeat;
        background-size:cover;
        opacity : 0.5;
    }
     .top
     {
        padding: 2px;
        color:black ;
        height: 106px;
        margin-top: 0px;
        background: white;

     }
      .lead{
          float:right;
      }
      .sign{
          float: right;
      }

  </style>
</head>
<body>
<div class="container">
  <% if member_signed_in? %>
    <div style="float:right;">
        <p>you have succesfully signed in<p>
      <div class="btn btn-default"><%= link_to "Sign Out", destroy_member_session_path, :method => :delete %></div>
      <div style="float:left ">
        <div class="btn btn-default"><%= link_to "Contact", "contact" %></div>
      </div>
    </div>



      <h1>Welcome to Customer Relationship Management Tool</h1>
      <div class="lead">
      <div class="btn btn-default"><%= link_to "Lead1", {:controller => "lead1s"} %></div>
      <div class="btn btn-default"><%= link_to "Lead2", {:controller => "lead2s"} %></div>
      <div class="btn btn-default"><%= link_to "Lead3", {:controller => "lead3s"} %></div>
      <div class="btn btn-default"><%= link_to "Lead4", {:controller => "lead4s"} %></div>
      <div class="btn btn-default"><%= link_to "Lead5", {:controller => "lead5s"} %></div>
    </div>



  <% else %>
   <div class="top">
    <h1>Welcome to Customer Relationship Management Tool </h1>
    <h5>Build a better relation</h5>
       <div class="sign">
        <%= link_to "Sign In", new_member_session_path, :method => :get %> &nbsp &nbsp &nbsp
        <%= link_to "Sign up", new_member_registration_path, :method => :get %>
       </div>
   </div>
  <% end %>
</div>
</body>
</html>