config/routes.rb
Crm::Application.routes.draw do
  devise_for :members

  resources :lead5s

  resources :lead4s

  resources :lead3s

  resources :lead2s

  resources :lead1s
  root :to =>'home#index'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

end

app/models/contact.rb
class Contact
  # attr_accessible :title, :body
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

    def new
      @contact = Contact.new

    end

    def create
      @contact = Contact.new(params[:contact])

      if @contact.valid?
        NotificationsMailer.new_contact(@contact).deliver
        redirect_to(root_path, :notice => "Message was successfully sent.")
      else
        flash.now.alert = "Please fill all fields."
        render :new
      end
    end



end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/new.html.erb
<div class="container">
<h1 style="padding-left: 30px"> Contact us</h1>
<div class="span6">
<%= form_for @contact, :url => contact_path do |form| %>


    <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>

    <fieldset class="fields">
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
      </div>
      <div class="field">
        <%= form.label :subject %>
        <%= form.text_field :subject %>
      </div>

      <div class="field">
        <%= form.label :body %>
        <%= form.text_area :body %>
      </div>
    </fieldset>

    <fieldset class="actions">
      <%= form.submit "Send" %>
    </fieldset>
<% end %>
</div>

<div class="span4">
  <div style="float: right"><%= link_to "back",  {:controller => "home", :action => "index"} %></li></div>
  <h3>What We Offer</h3>
  <p>A company that invests in you, trains you, sends you to conferences and pushes you to grow.</p>
  <p>Work on the brilliant ideas around the world. Work with startups which are innovating like hell, contribute your own.</p>
  <p>Work smart, so that you can have a fine balance between life and work.</p>
  <p>An opportunity to work on cutting edge technologies and products in a challenging, but informal work environment.</p>
  <p>A team that is young, passionate, skilled and open. A team which knows how to have fun on job.</p>
  <p>Come work in an environment that will inspire and motivate you.</p>
</div>
</div>